name: happy_luna
description:  A short & sweet game made for the 1st Flame Engine Game Jam.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bonfire: ^1.9.4
  cubes: ^1.2.1
  flame_splash_screen: ^0.1.0
  flame_audio: ^1.0.0-rc.15
  animated_text_kit: ^4.2.1
  maze: ^3.0.0
  scratcher: ^2.1.0
  flutter_animator: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - lang/
   - assets/images/
   - assets/audio/
   - assets/audio/bgm/
   - assets/audio/sfx/
   - assets/images/player/
   - assets/images/tiled/
   - assets/images/decoration/
   - assets/images/npc/

  fonts:
    - family: Butterfly
      fonts:
        - asset: fonts/ButterflyKids-Regular.ttf
    - family: Princess
      fonts:
        - asset: fonts/PrincessSofia-Regular.ttf
